- name: setup roboshop project
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load frontend role
      role: frontend

- name: setup roboshop project
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: Load MongoDb role
      role: mongodb

- name: Setup roboshop project -- Catalogue Component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - name: Load Catalogue Role
      role: catalogue

- name: Setup roboshop project -- redis Component
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - name: Load redis Role
      role: redis

- name: Setup roboshop project -- user Component
  hosts: USER
  become: yes
  tags:
    - user
  roles:
    - name: Load user Role
      role: user

- name: Setup roboshop project -- cart Component
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - name: Load cart Role
      role: cart

- name: Setup roboshop project -- MySql Component
  hosts: MYSQL
  become: yes
  tags:
    - mysql
  roles:
    - name: Load mysql Role
      role: mysql

- name: Setup roboshop project -- shipping Component
  hosts: SHIPPING
  become: yes
  tags:
    - shipping
  roles:
    - name: Load shipping Role
      role: shipping